{{- range .Values.configmaps }}
{{ $configmaps := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmaps.name }}
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    namespace: ms-{{ $.Values.global.app_name }}
    bu: {{ $.Values.global.bu }}
    release: {{ $.Release.Name }}
    releaseNumber: {{ $.Values.global.releaseNumber | quote }}
    managed-by: "harness"
    {{- range $key, $value := $configmaps.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if $configmaps.annotations }}
  annotations:
    {{- range $key, $value := $configmaps.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
data:
  {{- range $key, $value := $configmaps.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
