{{- with .Values.global }}
{{- if eq (kindOf .externalSecrets) "map" }}
{{- if .externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: envs-secretstore
  namespace: ms-{{ .app_name }}
  labels:
    namespace: ms-{{ .app_name }}
    bu: {{ .bu }}
    backstage.io/kubernetes-id: ms-{{ .app_name }}
    release: {{ $.Release.Name }}
    releaseNumber: {{ .releaseNumber | quote }}
    managed-by: "harness"
spec:
{{- if eq (.externalSecrets.type | default "aws") "vault" }}
  provider:
    vault:
      version: v2
      server: {{ .externalSecrets.server | default "https://vus.work/" }}
      auth:
       kubernetes:
        mountPath: {{ .externalSecrets.mountPath }}
        role: {{ .externalSecrets.role | default "role-reader-app" }}
      path: {{ .externalSecrets.path }}
{{- else }}
  provider:
    aws:
      service: SecretsManager
      region: {{ .externalSecrets.secretStore.region | default "us-east-1" quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .app_name }}-external-secrets
{{- end }}
{{- end }}
{{- end }}
{{- end }}
