{{- with .Values.global }}
  {{- if eq (kindOf .externalSecrets) "slice" }}
    {{- range $index, $externalSecret := .externalSecrets }}
      {{- if $externalSecret.enabled }}
        {{- if ne ($externalSecret.type | default "aws") "vault" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.global.app_name }}-{{ $externalSecret.name }}
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    bu: {{ $.Values.global.bu }}
    release: {{ $.Release.Name }}
    releaseNumber: {{ $.Values.global.releaseNumber | quote }}
    managed-by: "harness"
  annotations:
    eks.amazonaws.com/role-arn: {{ $externalSecret.roleArn }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}