{{- with .Values.global }}
{{- if eq (kindOf .externalSecrets) "map" }}
{{ if .externalSecrets.enabled }}
{{- if ne (.externalSecrets.type | default "aws") "vault" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .app_name }}-external-secrets
  namespace: ms-{{ .app_name }}
  labels:
    release: {{ $.Release.Name }}
    releaseNumber: {{ .releaseNumber | quote }}
    managed-by: "harness"
  annotations:
    eks.amazonaws.com/role-arn: {{ .externalSecrets.roleArn }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}