{{- if $.Values.global.jvm_metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if $.Values.global.jvm_metrics.annotations }}
  annotations:
    {{- range $key, $value := $.Values.global.jvm_metrics.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ $.Values.global.app_name }}-service-jvm-metrics
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    app: {{ $.Values.global.app_name }}-jvm-metrics
    jvm-metrics: enabled
    release: {{ $.Release.Name }}
    releaseNumber: {{ $.Values.global.releaseNumber | quote }}
    managed-by: "harness"
spec:
  ports:
  - port: {{ $.Values.global.jvm_metrics.port }}
    protocol: TCP
    targetPort: {{ $.Values.global.jvm_metrics.port }}
    name: exporter
  selector:
    jvm-metrics: enabled
    namespace: ms-{{ $.Values.global.app_name }}
  sessionAffinity: None
  type: {{ default "ClusterIP" $.Values.global.jvm_metrics.type }}
{{- end }}
