{{- range .Values.apis }}
{{ $api := . }}
{{- if $api.podDisruptionBudget }}{{ if $api.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Values.global.app_name }}-{{ $api.name }}-pdb
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    namespace: ms-{{ $.Values.global.app_name }}
    bu: {{ $.Values.global.bu }}
    app: {{ $.Values.global.app_name }}-{{ $api.name }}
    release: {{ $.Release.Name }}
    releaseNumber: {{ $.Values.global.releaseNumber | quote }}
    managed-by: "harness"
spec:
  minAvailable: {{ $api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ $.Values.global.app_name }}-{{ $api.name }}
{{- end }}{{ end }}
{{- end }}
