{{- if not (empty $.Values.global.api_roleArn) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.global.app_name }}-api-sa
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    namespace: ms-{{ $.Values.global.app_name }}
    bu: {{ $.Values.global.bu }}
    release: {{ $.Release.Name }}
    releaseNumber: {{ $.Values.global.releaseNumber | quote }}
    managed-by: "harness"
    backstage.io/kubernetes-id: ms-{{ $.Values.global.app_name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.global.api_roleArn | default "" }}
{{- end }}