{{- range .Values.apis }}
{{ $api := . }}
{{- if ($api.multiPortService).enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if $api.multiPortService.annotations }}
  annotations:
    {{- range $key, $value := $api.multiPortService.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ $.Values.global.app_name }}-{{ $api.name }}
  namespace: ms-{{ $.Values.global.app_name }}
  labels:
    namespace: ms-{{ $.Values.global.app_name }}
    bu: {{ $.Values.global.bu }}
    release: {{ $.Release.Name }}
    releaseNumber: {{ $.Values.global.releaseNumber | quote }}
    managed-by: "harness"
    backstage.io/kubernetes-id: ms-{{ $.Values.global.app_name }}
    {{- if $api.labels }}{{ toYaml $api.labels | nindent 4}}{{- end }}
spec:
  ports:
  {{- range $api.multiPortService.ports }}
  - port: {{ .port }}
    protocol: TCP
    targetPort: {{ .targetPort }}
    {{- if not (empty .name) }}
    name: {{ .name }}
    {{- end}}
  {{- end }}
  selector:
    app: {{ $.Values.global.app_name }}-{{ $api.name }}
  sessionAffinity: None
  type: {{ default "ClusterIP" $api.multiPortService.type }}
{{- end }}
{{- end }}
