{{- if and .Values.restartFailedTasks.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-failed-tasks
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  jobTemplate:
    metadata:
      name: restart-failed-tasks
    spec:
      template:
        spec:
          containers:
            - image: {{ .Values.restartFailedTasks.image }}
              name: restart-failed-tasks
              command: ["/bin/sh"]
              args: ["/etc/scripts/restart-failed-tasks.sh"]
              volumeMounts:
                - name: kafka-connect-scripts
                  mountPath: /etc/scripts
              resources:
{{ toYaml .Values.restartFailedTasks.resources | indent 16 }}
          volumes:
            - name: kafka-connect-scripts
              configMap:
                name: kafka-connect-scripts
          restartPolicy: OnFailure
          {{- if .Values.tolerations }}
          tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
          {{- end }}
          {{- if .Values.affinity }}
          affinity:
{{ toYaml .Values.affinity | indent 12 }}
          {{- end }}
  schedule: {{ .Values.restartFailedTasks.schedule }}
{{- end }}
