{{- if .Values.webui.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-connect-ui
  name: kafka-connect-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-ui
  template:
    metadata:
      labels:
        app: kafka-connect-ui
    spec:
      containers:
        - image: {{ default "landoop/kafka-connect-image" .Values.webui.image }}
          name: kafka-connect-ui
          ports:
            - containerPort: {{ default "8000" .Values.webui.servicePort }}
              name: http
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 32Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: CONNECT_URL
              value: http://{{ template "cp-kafka-connect.fullname" . }}:{{ .Values.servicePort }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-ui
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: kafka-connect-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ default "internal-microservices" .Values.webui.ingressClass }}
  name: kafka-connect-ui
spec:
  rules:
  {{- if .Values.webui.host }}
    - host: {{ .Values.webui.host }}
  {{- else }}
    - host: {{ template "cp-kafka-connect.fullname" . }}.ms.{{ .Values.global.app_stage }}
  {{- end}}
      http:
        paths:
          - backend:
              service:
                name: kafka-connect-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
{{- end }}